# 2_Numpy Exercise

### 1) Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [2]:
import numpy as np

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

### 2) Write a NumPy program to create an array of all the even integers from 30 to 70.

In [14]:
np.arange(30,71,2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

### 3) Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.


In [40]:
a= np.ones((10,10))    #create an 10*10 matrix of ones
a [1:-1,1:-1] = 0      #Change inner Rows and Columns to 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### 4) Write a NumPy program to reverse an array (first element becomes last).

In [56]:
#Original table
ori = np.arange(12,38)
ori

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

In [61]:
ori[::-1]

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

### 5) Write a NumPy program to find common values between two arrays.

In [77]:
A1= np.array([ 0 ,10, 20,40 ,60])

In [78]:
A2= np.array([10, 30, 40])  

In [82]:
print(np.intersect1d (A1, A2))

[10 40]


### 6) Write a NumPy program to create an array. Then change it to a new shape of the array, without changing its data.


In [87]:
array_6 = np.arange(12)
array_6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [88]:
array_6.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [89]:
np.reshape(array_6,(2,2,3))

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

###  7) Write a NumPy program to concatenate two 2-dimensional arrays in the following manner as below.



In [92]:
a1= np.array([[0,1,3],[5,7,9]])

In [94]:
a2= np.array([[5,7,9],[6,8,10]])

In [104]:
np.concatenate((a1,a2),1)

array([[ 0,  1,  3,  5,  7,  9],
       [ 5,  7,  9,  6,  8, 10]])

### 8) Write a NumPy program to split an array of 14 elements into 3 arrays, each of which has 2, 4, and 8 elements in the original order.


In [4]:
array8= np.arange(14)

In [6]:
print(np.split(array8,[2,6]))

[array([0, 1]), array([2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11, 12, 13])]


### 9) Write a NumPy program to create an 1-D array of 20 elements. Now create a new array of shape (5, 4) from the said array, then restores the reshaped array into a 1-D array.


In [14]:
z= np.arange(20)
print('Original array')
print(z)

print('New array of shape(5,4)')
new_array = z.reshape(5,4)
print(new_array)

print('Restore the reshaped array into a 1-D array:')
print(new_array.flatten())

Original array
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
New array of shape(5,4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
Restore the reshaped array into a 1-D array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


### 10) Write a NumPy program to create an array of 4,5 shape and swap column1 with column4.


In [31]:
print('original array')
x = np.arange(20).reshape(4,5)
print(x)

print('After swapping column1 with column4:')
x[:,[0,3]] = x[:,[3,0]]
print(x)

original array
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
After swapping column1 with column4:
[[ 3  1  2  0  4]
 [ 8  6  7  5  9]
 [13 11 12 10 14]
 [18 16 17 15 19]]
